<?php

namespace AppBundle\Repository;

/**
 * Lead_uniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Lead_uniRepository extends \Doctrine\ORM\EntityRepository
{
}
