# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.kernel_listener:
        class: AppBundle\EventListener\KernelListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelRequest }
        arguments: [ "@doctrine" ]
            
    app.admin.builder.orm_datagrid:
        class: AppBundle\CustomFunc\DatagridBuilder
        arguments: ["@form.factory", "@sonata.admin.builder.filter.factory", "@sonata.admin.guesser.orm_datagrid_chain",%form.type_extension.csrf.enabled% ]